apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tethys-app.fullname" . }}-portal-config
  labels:
    {{- include "tethys-app.labels" . | nindent 4 }}
data:
  portal_config.yml: |
{{ include "tethys-app.portalConfigContent" . | indent 4 }}
